import os, sys  # noqa: E401
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import streamlit as st

from lib import TITLE, setup

setup("About", "ℹ️")
st.title("About this study")
st.markdown(f"""
**Manuscript:** *{TITLE}* (under review).

### Data
* 598 English-language TripAdvisor reviews (including TripAdvisor's English machine translations) of 14 tourism
  entities in İzmir Province, Turkey, in six categories: Accommodation, Beach/Coastal, Food/Gastronomy,
  History/Culture, Nature and Nightlife. Collected manually in September 2026 using TripAdvisor's rating filters.
* Labels follow the star rating (1–2 Negative, 3 Neutral, 4–5 Positive) with eight documented manual overrides, and
  were checked with a blind two-annotator audit.
* Each entity's full rating histogram (13,209 ratings, all languages) is used for destination-level results.
* Only review text, star rating, entity and category were recorded; no usernames, profiles or dates.
  **Review texts are not redistributed** because of TripAdvisor's terms of use.

### Methods in brief
* Locked stratified split 418 / 90 / 90; every choice made on validation macro-F1 only; neural models run with five seeds.
* Models: VADER, TF-IDF + logistic regression, TF-IDF + linear SVM, multi-kernel CNN, BiLSTM, fine-tuned DistilBERT.
* Uncertainty: bootstrap confidence intervals (2,000 resamples), exact McNemar tests with Holm correction,
  pooled random 5-fold and leave-one-entity-out cross-validation.
* Destination analysis: post-stratification to each entity's rating distribution, χ² with Cramér's V, NMF topics
  with coherence-based selection.

### Reproducibility
Code, results and this app: https://github.com/skunateh7/Izmir-tourism-sentiment

Every table and figure is regenerated by the numbered scripts in the repository (`scripts/01` … `scripts/12`);
this app only reads their outputs in `results/`. The classifier page uses TF-IDF models refitted by
`scripts/13_export_app_models.py`, which checks that they reproduce the manuscript's test scores exactly.

### Use of AI tools
Claude (Anthropic; Claude Opus 5.5) assisted with writing and checking the analysis code, the statistical workflow,
the figures and this app, and proposed provisional error-analysis categories that the author reviewed. ChatGPT
(OpenAI; GPT-5.6 Sol) was used by the second annotator only to draft notes on labels already assigned, and by the
author for feedback on manuscript drafts. No AI tool assigned any sentiment label; the author verified all results.

### Citation
If you use this work, please cite the article once published (citation details will be added here).
""")
